FROM node:22-alpine

ARG SSL_COMMON_NAME=localhost
ARG PORT=3000

WORKDIR /backend

COPY . .

ENV SSL_COMMON_NAME=$SSL_COMMON_NAME
ENV PORT=$PORT

RUN chmod +x ./setup.sh && ./setup.sh
RUN chmod +x ./wait-for-db.sh

EXPOSE ${PORT}

CMD ["node", "index.js"]
ENTRYPOINT ["./wait-for-db.sh"]


