FROM node:22-alpine

ARG SSL_COMMON_NAME=localhost
ARG PORT=3000

WORKDIR /backend

COPY . .

ENV SSL_COMMON_NAME=$SSL_COMMON_NAME
ENV PORT=$PORT

RUN chmod +x ./docker/scripts/setup.sh && ./docker/scripts/setup.sh
RUN chmod +x ./docker/scripts/wait-for-db.sh

EXPOSE ${PORT}

CMD ["node", "index.js"]
ENTRYPOINT ["./docker/scripts/wait-for-db.sh"]


