FROM node:22-alpine

ARG PORT=8080

WORKDIR /backend

COPY . .

ENV PORT=$PORT

RUN npm cache clean --force && npm install --verbose
RUN chmod +x ./docker/scripts/wait-for-db.sh

EXPOSE ${PORT}

CMD ["node", "index.js"]
ENTRYPOINT ["./docker/scripts/wait-for-db.sh"]